### ISSUE TITLE
Does not work on Mac nor Linux

### ISSUE THREAD

**Issue by jbejar** [JohnMasen/ChakraCore.NET#20] opened 2018-08-02 21:07 UTC
I would recommend removing the .dll from the name, similar to here:
https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/99d570642f7d3c3079e4ea2176b66b27b5d9987a/src/JavaScriptEngineSwitcher.ChakraCore/JsRt/NativeMethods.cs

**Comment by JohnMasen** [comment] 2018-08-04 15:35
thanks for your suggest, this is very helpful.
I'll fix it soon, or you can create a PR if you like.

**Comment by JohnMasen** [comment] 2018-08-05 15:03
a new release is published to nuget, please feel free to contact me if you found the issue is not fixed.

**Comment by JohnMasen** [comment] 2018-08-09 14:51
as there's no more comments on this issue, I'll close it for now

**Closed as completed by JohnMasen** 2018-08-09 14:51 UTC
